repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      exclude: ^setup.py
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8

- repo: https://github.com/baurt/precommit-dephell
  rev: master
  hooks:
    - id: pyproject-toml-to-setup-py
    - id: pyproject-toml-to-requirements-txt

