[tool.black]
exclude="setup.py"


[tool.poetry]
name = "flask_security"
version = "3.2.0rc4"
description =""" Flask-Security is an opinionated Flask extension which adds basic
  security and authentication features to your Flask apps quickly
  and easily"""
authors = ["Matt Wright <matt@nobien.net>", "Chris Wagner <jwag.wagner@gmail.com>"]
license = "MIT"
repository = "https://github.com/jwag956/flask-security"
documentation = "https://flask-security-too.readthedocs.io"
readme = "README.rst"
classifiers=[
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Development Status :: 4 - Beta",
]

[tool.poetry.dependencies]
python = "~2.7||^3.5"
Flask=">=0.12"
Flask-Login=">=0.3.0"
Flask-Mail=">=0.9.1"
Flask-Principal=">=0.4.0"
Flask-WTF=">=0.14.2"
Flask-BabelEx=">=0.9.3"
itsdangerous=">=1.1.0"
passlib=">=1.7.1"
cachetools = ">=3.1.0"


[tool.poetry.dev-dependencies]
Babel = ">=2.7.0"
bcrypt = ">=3.1"
check-manifest = ">=0.25"
coverage = ">=4.0"
cryptography = ">=2.3.0"
flake8 = ">=3.7"
Flask-CLI = ">=0.4.0"
Flask-Mongoengine = ">=0.9.5"
Flask-Peewee = ">=0.6.5"
Flask-Sphinx-Themes= ">=1.0.1"
Flask-SQLAlchemy = ">=2.3"
isort = ">=4.2.2"
mock = ">=1.3.0"
mongoengine = ">=0.12.0"
mongomock = ">=3.14.0"
msgcheck = ">=2.9"
pony = ">=0.7.4"
pre-commit = ">=1.16"
psycopg2 = ">=2.7.4"
pydocstyle = ">=1.0.0"
pymysql = ">=0.9.3"
pyqrcode=">=1.2"
pytest-black = ">=0.3.7"
pytest-cache = ">=1.0"
pytest-cov = ">=2.5.1"
pytest-flake8 = ">=1.0.4"
pytest-runner = ">=2.6.2"
pytest = ">=3.5.1"
Sphinx = ">=1.4.2"
sphinx-issues = ">=1.2.0"
sqlalchemy = ">=1.1.0"
sqlalchemy-utils = ">=0.33.0"
tomlkit = ">=0.5.3"
tox = ">=3.12"
werkzeug = ">=0.12.2"

[tool.poetry.extras]
docs = ["Sphinx","Flask-Sphinx-Themes","sphinx-issues","tomlkit"]
tests = [
  "Babel",
  "Flask-CLI",
  "Flask-Mongoengine",
  "Flask-Peewee",
  "Flask-SQLAlchemy",
  "bcrypt",
  "check-manifest",
  "coverage",
  "cryptography",
  "isort",
  "mock",
  "mongoengine",
  "mongomock",
  "msgcheck",
  "pony",
  "psycopg2",
  "pydocstyle",
  "pymysql",
  "pyqrcode",
  "pytest-black",
  "pytest-cache",
  "pytest-cov",
  "pytest-flake8",
  "pytest-mongo",
  "pytest-runner",
  "pytest",
  "Sphinx",
  "Flask-Sphinx-Themes",
  "sphinx-issues",
  "sqlalchemy",
  "sqlalchemy-utils",
  "tomlkit",
  "werkzeug"
]


# [build-system]
# requires = ["poetry>=0.12"]
# build-backend = "poetry.masonry.api"

[tool.dephell.main]
# read from poetry format
from = {format = "poetry", path = "pyproject.toml"}
# and convert into setup.py
to = {format = "setuppy", path = "setup.py"}
